# Nixpacks configuration for Railway deployment
# This helps Railway understand how to build and start the backend

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
